baseURL: https://kaiyuanli.netlify.app/
languageCode: en-us
title: Portfolio website for Kaiyuan Li
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
       -- I'm a student in London Business School studying Analytics Management.         
       This is my personal website where I'll share my progress and everything about me --
    title: Hi, my name is Kaiyuan Li
  blog: {}
  contact: 
    address: 
      - city: London NW1
        country: UK
        street: Baker Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wli.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Kaiyuan Li
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/kyss_hhqy
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100085575019956
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/kaiyuanl0920
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/kaiyuan-li-0920
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/kaiyuanl
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
      #  url: blogs/ipsum
      #- name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: By Kaiyuan Li
    title: Website
  tiles:
    enable: yes
    showcase:
      - image: DSC_9511_20220525_205628.jpg
        subtitle: Everything about myself
        title: About Me
        url: blogs/About_Kaiyuan
        
      - image: IMDB.jpg
        subtitle: What are the ratings between different genres and directors?
        title: IMDB Rating Analysis
        url: blogs/IMDB_Ratings
        
      - image: Biden.jpg
        subtitle: How does Biden's approval rate change in 2022?
        title: Biden's Approval Margins
        url: blogs/Biden-s-Approval-Rate
        
      - image: Risk_Return.jpg
        subtitle: Risk and return analysis for DJIA Stocks
        title: Risk and Return
        url: blogs/risk_return
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
#    buttonText: Get Started
#    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
#    title: Massa libero
#    url: blogs
